language: java

install:
    - mvn -DskipTests=true dependency:resolve

script:
    - mvn clean test

after_success:
    - mvn -DskipTests=true clean package

deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: ./target/ic-amqp-plugin.zip
    skip_cleanup: true
    on:
        tags: true
